### PR TITLE
Update Main Pages “supporters”

### PR DESCRIPTION
**Pull request by jimmytipit**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by grahamwhaley** [comment]
well, as this is an auto-generated CMS series of patches, in HTML, with no commit descriptions or viewable render.... it's pretty hard to review.
And, as we know, the CMS does not have the ability to follow our CI requirements, such as signing off commits.
I don't know what we will do here long term, apart from using trust and force merges....

**Comment by jimmytipit** [comment]
Graham, I sent an email on this, but never heard back. Basically, Netlify doesn't currently allow for signed requests, as you mentioned.  However, our marketing team needs to be able to work through the CMS as they aren't all up to speed on git.  The CMS itself offers a live preview, so if the request is coming from the CMS, you can be sure that it's been reviewed.

I'd like to suggest we remove the qualification for signed commits on the kata website.  There are only a small number of people making changes anyway, and unlike a software project, it's strictly marketing and mostly text updates.

**Comment by grahamwhaley** [comment]
Hi @jimmytipit - ack, sorry for lack of reply. I suspect we can drop the signed of by check, but it will nominally break our projects [chain of trust rules](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#certificate-of-origin) for contributions...
Sure, the web site core data is a little different from the rest of the project, given afaik there is a small well defined core set of contributors, all related to the OSF....

So, I think we need to have some of the @kata-containers/architecture-committee chip in on this, and get enough acks to 'make it so'. We should add a note in the repo top level document, and make a PR to educate the CI about this singular special case...

**Comment by jimmytipit** [comment]
Thanks @grahamwhaley I appreciate the consideration!  Should I post to the ml or this is something you'd like to raise directly with the architecture committee?

**Comment by grahamwhaley** [comment]
Hopefully they saw the post here, and will respond... - the reference in the message should land a ping in their intrays ;-)
If that fails, best way to push it forwards would be to put it in the [arch committee agenda](https://etherpad.openstack.org/p/Kata_Containers_2020_Architecture_Committee_Mtgs), where it should then get picked up in the weekly conf call. Add a link to this PR/Issue.
Let's give it a couple of days, and if nothing happens, push it into the agenda.

**Comment by jimmytipit** [comment]
Awesome.  Thanks again @grahamwhaley !!

**Comment by grahamwhaley** [comment]
Hi @jimmytipit - I raised the question on todays arch call, and there were no objections to me reducing the CI checks to the level where your CMS pushes are reasonably painless...
I'll stare at that in the next couple of days and let you know how it goes. I'll likely also update the front page docs on this repo to note the reduced/relaxed checks are in place.

**Pull request closed without merging**
