### PR TITLE
Update slack channel URL to point to invite URL

### PR DESCRIPTION
**Pull request by mrhillsman**
Closes issue #33

### CODE REVIEW

**Comment by jbryce** [comment]
I'd like to add an invite link rather than just replacing the main slack workspace link. What do you think about that approach?

Also, you need to add a signed off by header to your commit. You can do this by adding -s to your git commit command.

**Comment by mrhillsman** [comment]
Yeah, that makes sense, because if I go to the invite URL and enter my address it still sends me an invite even though I have already been approved and joined the workspace.

Noticed that, should this be added to the contribute page? I clicked on the contribute link when I opened the issue but did not know about the signed-off requirement until the failed check here.

**Comment by jbryce** [comment]
Yes, we should document the signed off requirement upfront somewhere too.

**Comment by grahamwhaley** [comment]
Just for reference, we have wordage over in ClearContainers around that:
https://github.com/clearcontainers/runtime/blob/master/CONTRIBUTING.md#patch-format
fee free to liberate if you need.

**Comment by mrhillsman** [comment]
Nice! Unfortunately no way it seems to provide organization wide templates :(

**Comment by mrhillsman** [comment]
How about this @jbryce [https://imgur.com/y7n3dll](https://imgur.com/y7n3dll)

**Comment by jbryce** [comment]
I like it. Thanks!

**Comment by sameo** [comment]
LGTM

**Pull request merged**
