### PR TITLE
Fixed link to git repo

### PR DESCRIPTION
**Pull request by jimmytipit**
Signed-off-by: Jimmy McArthur <jimmy@tipit.net>

### CODE REVIEW

**Comment by gbraad** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Comment by gbraad** [comment]
Fixes #20

**Comment by jodh-intel** [comment]
lgtm.

However, the pullapprove check is complaining due to the merge commit. I think you need to remove that merge commit doing something like the following which is in line with what pullapprove is expecting:

```
git rebase master
git push -f
```

**Pull request closed without merging**
