### PR TITLE
subsystem: Replace URL of Blog in nav w/ URL for medium.com

### LINKED ISSUE #97: Replace hyperlink in top-level "BLOG" with https://medium.com/kata-containers
# Bug report

On [katacontainers.io](https://katacontainers.io/), **change** hyperlink in top-level nav button "BLOG"...

from: https://katacontainers.io/community/
to: https://medium.com/kata-containers

Current design implies redundant behavior. 

**If the current behavior is a bug, please provide the steps to reproduce.**

NA

**What is the expected behavior?**

From the homepage, users should click BLOG and go directly to: https://medium.com/kata-containers

If a user is on the [Community page](https://katacontainers.io/community/), a user has two methods to reach the `medium.com/kata-containers` page.  Currently, a user must select the link "View the full blog" to go directly to the medium-hosted blogposts. In addition, from a user-nav standpoint,  the assumption is that a user must got to the Community page to go to the full set of blogposts.

Providing users with too many paths to reach the same page, and using redundant links, is confusing.  Reduce the number of clicks to reach the desired page. Simplify and streamline user-nav.

**Other relevant information:**

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

### PR DESCRIPTION
**Pull request by mvincerx**
- Closes #97

Signed-off-by: Michael Vincerra <michael.vincerra@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Odd, I don't see any files changed in the commit - but, hey, maybe it's CMS magic? :-)

**Comment by mvincerx** [comment]
@grahamwhaley  Thanks for reviewing. Not sure what happened. I fixed it now. Cheers.

**Comment by grahamwhaley** [comment]
@jimmytipit - presume this is your domain - ptatl...

**Comment by mvincerx** [comment]
@jimmytipit ping. Do you have feedback on this?

**Comment by jimmytipit** [comment]
Hi y'all. I wish it made this much sense.  However, redirects are done here: https://github.com/kata-containers/www.katacontainers.io/blob/master/netlify.toml  You can see the format in the code there, but let me know if you'd like me to take care of it.

**Comment by mvincerx** [comment]
Thanks @jimmytipit. Given that this must be a redirect, I vote for changing it where you stated: https://github.com/kata-containers/www.katacontainers.io/blob/master/netlify.toml.

I believe I can just add a new line for a redirect in the `netlify.toml`, after Ln 12, correct? 
Just say the word if so, and I'll close this PR and create a new PR that captures above changes.

**Comment by jimmytipit** [comment]
Working on fixing this.  Should have the redirect up by EOD and everything working properly.

**Comment by mvincerx** [comment]
Thanks, @jimmytipit. I noticed that you recently added the redirect to the [netlify.toml](https://github.com/kata-containers/www.katacontainers.io/blob/master/netlify.toml). 

Does your latter change **render moot the change of this PR**? Or will this PR be necessary? 
I noticed yesterday that clicking the top-level `BLOG` button produces and empty page:

blog-link-empty

Perhaps you're already working on this.

**Comment by jimmytipit** [comment]
Yes, the updates we've made will moot  this PR.  I've kept it open for communication purposes.  We're still working on the problem though.  Since there is a built-in blogging tool in Netlify that Kata isn't using, there are some additional issues with the redirect.  Hope to have a fix by EOD.

**Comment by mvincerx** [comment]
Thanks for the update, @jimmytipit.  Looking forward to the fix. 🥳

**Comment by gcutrini** [comment]
@jimmytipit the change introduced by this PR correctly solves the outbound redirect from the nav link.
The redirect set in netlify.toml serves the purpose of issuing the redirect ahead of the webpage  loading.

**Comment by jimmytipit** [comment]
Alrighty everyone.  You should see this if you clear your cache (or Ctrl/Command + F5)

Thanks to @gcutrini for the assist.

**Comment by mvincerx** [comment]
Works nicely now. `CTRL+R` is a reflex, not a nerve. :) Thanks for the clarification, @gcutrini. 
Thanks, @jimmytipit for your help.

**Pull request merged**
