### PR TITLE
Update to Kata Slack URL

### PR DESCRIPTION
**Pull request by jimmytipit**
- Modified URL

### CODE REVIEW

**Comment by jimmytipit** [comment]
@JpMaxMan can you review this and approve? It's a simple URL update.

**Comment by egernst** [comment]
@jimmytipit  can you add SOB?

**Comment by gnawux** [comment]
Yep, but we need a sign-off to merge it.

**Comment by jodh-intel** [comment]
Hi @jimmytipit - please add a [`Signed-off-by:`](https://github.com/kata-containers/community/blob/a6198e2e4cf871783beb9a2c1659fdb3129af9f0/CONTRIBUTING.md#certificate-of-origin) comment to your commit so it looks something like:

```
comms: Update to Kata Slack URL

The Slack invitation URL expired (boo!) so update to the new one.

Signed-off-by: Your name <your-name@somewhere.com>
```

I've updated the other mention of the Slack URL (which I do think we should retain) on https://github.com/kata-containers/community/pull/131.

**Comment by jimmytipit** [comment]
So I amended this and signed it, but it looks like it ended up as a separate commit. I'm tempted to just close and re-PR.

**Pull request closed without merging**
